export const GET_BRANDS = 'GET_BRANDS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAIL = 'GET_BRANDS_FAIL';

export const POST_BRAND = 'POST_BRAND';
export const POST_BRAND_SUCCESS = 'POST_BRAND_SUCCESS';
export const POST_BRAND_FAIL = 'POST_BRAND_FAIL';

export const EDIT_BRAND = 'EDIT_BRAND';
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS';
export const EDIT_BRAND_FAIL = 'EDIT_BRAND_FAIL';

export const DELETE_BRAND = 'DELETE_BRAND';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';

export const SEARCH_BRANDS = 'SEARCH_BRANDS';
export const SEARCH_BRANDS_SUCCESS = 'SEARCH_BRANDS_SUCCESS';
export const SEARCH_BRANDS_FAIL = 'SEARCH_BRANDS_FAIL';
